export enum LimitTypeEnum {
  ACCOUNT_LIMIT = 'ACCOUNT_LIMIT',
  PER_TRANSACTION_LIMIT = 'PER_TRANSACTION_LIMIT',
}
export enum OfferStatusEnum {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
}
